### ISSUE TITLE
Add Composer

### ISSUE THREAD

**Issue by XedinUnknown** [codersrank-org/libraries#45]
## The Problem
There is no library defined for PHP's [Composer][]; and yet, it is a very important part of programming in PHP, because this is how PHP packages are defined and shared.

Furthermore, a technology for "Dependency Management" is missing altogether.

## Suggested Solution
Add "Composer" library, associated with "Dependency Management" technology. The language is probably JSON.

## Remarks
I am not exactly sure what is the definition of "library" here. Composer is not a library. Neither is ASP.NET. But I guess it fits under what I understood as the definition of "library" in this context.

[Composer]: https://getcomposer.org/

**Comment by peti2001** [comment]
It was a design decision not to use Dependency management There are 2 reasons for it.
1. In many cases, it is very hard to find the file that describes the dependencies because it is not in the root folder. For example, monorepos, when there might be many dependency files. Finding all of them is an expensive operation.
This is why we decided to parse the source code and define the import rules for every language. You can find the implemented languages here: https://github.com/codersrank-org/repo_info_extractor/tree/master/src/language
PHP is missing and we already have a ticket for that: https://github.com/codersrank-org/repo_info_extractor/issues/42

2. If we analyze only the dependency file it is not possible to detect the usage of a given library. We can detect the dependencies of a repository but we cannot detect how often you used that library.

This is still not solved but duplicated so I close it.

**Comment by XedinUnknown** [comment]
Understood. Thanks for looking into this!
